###
POST http://localhost:3000/api/routes/users HTTP/1.1
Content-Type: application/json

{
  "name": "Alfredo",
  "lastname": "Gonzalez",
  "email": "74783123@itesa.edu.mx",
  "password": "admin123",
  "role":"author"
}

###
GET http://localhost:3000/api/routes/users   HTTP/1.1


###
GET http://localhost:3000/api/routes/users/6451c6109266427ccb15619a HTTP/1.1


###
PUT http://localhost:3000/api/routes/users/6451c6439266427ccb1561a0 HTTP/1.1
Content-Type: application/json

{
  "name": "alejo"
}


###
DELETE  http://localhost:3000/api/routes/users/6451c6439266427ccb1561a0  HTTP/1.1